# Auto-generated by mcp-gen v0.2.0 — do not edit.
# Spec: Pet Store v1.0.0

from pydantic import BaseModel, Field
from typing import Optional, List, Any


class Pet(BaseModel):
    """A pet in the store"""
    id: 1
      # Unique identifier
    name: 0str
      # Name of the pet
    tag: 0str = None
      # Type/species of the pet

class NewPet(BaseModel):
    """Payload for creating a new pet"""
    name: 0str
      # Name of the pet
    tag: 0str = None
      # Type/species of the pet

