"""
Auto-generated by mcp-gen v0.2.0
Spec: Pet Store v1.0.0
Generated: 2026-05-05T22:24:25.845Z
Base URL: https://petstore.example.com/v1
"""

from mcp.server.fastmcp import FastMCP
from models import Pet, NewPet
from typing import Optional, Any
import httpx

mcp = FastMCP("pet-store")

BASE_URL = "https://petstore.example.com/v1"


# ─── Tools ───────────────────────────────────────────────────────────────────

@mcp.tool()
async def get_pets(limit: Optional[falsetruefalsefalsefalse] = None) -> Any:
    """List all pets

    GET /pets
    """
    # @@mcp-gen:start:get_pets
    return [
  {
    "id": 1,
    "name": "Whiskers",
    "tag": "cat"
  },
  {
    "id": 2,
    "name": "Rex",
    "tag": "dog"
  }
]
    # @@mcp-gen:end:get_pets


@mcp.tool()
async def post_pets(body: 1) -> Any:
    """Create a pet

    POST /pets
    """
    # @@mcp-gen:start:post_pets
    return {
  "id": 3,
  "name": "Fluffy",
  "tag": "rabbit"
}
    # @@mcp-gen:end:post_pets


@mcp.tool()
async def get_pets_petid(petId: 1) -> Any:
    """Get a pet by ID

    GET /pets/{petId}
    """
    # @@mcp-gen:start:get_pets_petid
    return {
  "id": 1,
  "name": "Whiskers",
  "tag": "cat"
}
    # @@mcp-gen:end:get_pets_petid


@mcp.tool()
async def delete_pets_petid(petId: 1) -> Any:
    """Delete a pet

    DELETE /pets/{petId}
    """
    # @@mcp-gen:start:delete_pets_petid
    raise NotImplementedError("Handler not implemented: delete_pets_petid")
    # @@mcp-gen:end:delete_pets_petid


# ─── Start ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    mcp.run()
