// Auto-generated by mcp-gen — do not edit.
// Source: Pet Store v1.0.0

/** A pet in the store */
export interface Pet {
  id: number; // Unique identifier
  name: string; // Name of the pet
  tag?: string; // Type/species of the pet
}

/** Payload for creating a new pet */
export interface NewPet {
  name: string; // Name of the pet
  tag?: string; // Type/species of the pet
}

