import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ErrorCode,
  ListToolsRequestSchema,
  McpError,
} from "@modelcontextprotocol/sdk/types.js";

// Auto-generated by mcp-gen v0.2.0
// Spec: Pet Store v1.0.0
// Generated: 2026-05-05T22:24:32.752Z
// Incremental mode: edit code between @@mcp-gen markers — it will be preserved on re-generation.

const server = new Server(
  { name: "pet-store", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

// ─── Tool Definitions ────────────────────────────────────────────────────────

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "get_pets",
      description: "List all pets",
      inputSchema: {
        type: "object" as const,
        properties: {
          limit: { type: "number", description: "Maximum number of pets to return" },
        },
        required: [],
      },
    },
    {
      name: "post_pets",
      description: "Create a pet",
      inputSchema: {
        type: "object" as const,
        properties: {
          body: { type: "object", description: "Request body" },
        },
        required: ["body",],
      },
    },
    {
      name: "get_pets_petid",
      description: "Get a pet by ID",
      inputSchema: {
        type: "object" as const,
        properties: {
          petId: { type: "number", description: "The ID of the pet to retrieve" },
        },
        required: ["petId",],
      },
    },
    {
      name: "delete_pets_petid",
      description: "Delete a pet",
      inputSchema: {
        type: "object" as const,
        properties: {
          petId: { type: "number", description: "The ID of the pet to delete" },
        },
        required: ["petId",],
      },
    },
  ],
}));

// ─── Tool Handlers ───────────────────────────────────────────────────────────

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case "get_pets": {
      // GET /pets
      // @@mcp-gen:start:get_pets
      return {
        content: [{ type: "text" as const, text: JSON.stringify([
  {
    "id": 1,
    "name": "Whiskers",
    "tag": "cat"
  },
  {
    "id": 2,
    "name": "Rex",
    "tag": "dog"
  }
], null, 2) }],
      };
@@mcp-gen:end:get_pets
    }
    case "post_pets": {
      // POST /pets
      // @@mcp-gen:start:post_pets
      return {
        content: [{ type: "text" as const, text: JSON.stringify({
  "id": 3,
  "name": "Fluffy",
  "tag": "rabbit"
}, null, 2) }],
      };
@@mcp-gen:end:post_pets
    }
    case "get_pets_petid": {
      // GET /pets/{petId}
      // @@mcp-gen:start:get_pets_petid
      return {
        content: [{ type: "text" as const, text: JSON.stringify({
  "id": 1,
  "name": "Whiskers",
  "tag": "cat"
}, null, 2) }],
      };
@@mcp-gen:end:get_pets_petid
    }
    case "delete_pets_petid": {
      // DELETE /pets/{petId}
      // @@mcp-gen:start:delete_pets_petid
      throw new McpError(ErrorCode.InternalError, "Handler not implemented: delete_pets_petid");
      // @@mcp-gen:end:delete_pets_petid
    }
    default:
      throw new McpError(ErrorCode.MethodNotFound, `Unknown tool: ${name}`);
  }
});

// ─── Start ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`MCP Server "pet-store" running on stdio`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
