FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /server .

FROM alpine:3.20 AS runtime

WORKDIR /app
COPY --from=builder /server /server

ENV TOKEN=""

CMD ["/server"]